### ISSUE TITLE
WCT Test Error - TypeError: Cannot read property 'decl' of undefined

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#133]
Please walk through the following steps for reporting an issue about Orion:

## Short description of your issue:

When running WCT tests the following error intermittently happens: 

```
TypeError: Cannot read property 'decl' of undefined
    at /home/ubuntu/orion/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32:37
    at Array.forEach (native)
    at LcovOnlyReport.onDetail (/home/ubuntu/orion/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:30:28)
    at LcovReport.(anonymous function) [as onDetail] (/home/ubuntu/orion/node_modules/nyc/node_modules/istanbul-reports/lib/lcov/index.js:21:24)
    at Visitor.(anonymous function) [as onDetail] (/home/ubuntu/orion/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/home/ubuntu/orion/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /home/ubuntu/orion/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (native)
    at visitChildren (/home/ubuntu/orion/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/home/ubuntu/orion/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:126:5)

```

It happens locally on my machine and also on Circle CI (https://circleci.com/gh/orion-ui/orion/671?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Run the master branch CI build and wait for the error

## What browsers are affected?

N/A

## Which Orion version is affected?

N/A

**Comment by nfiniteset** [comment]
@camwest This is ready to merge. The branch is failing due to the Gemini issue Marc is working on. the unit specs pass!

**Comment by nfiniteset** [comment]
The solution was to exclude fixture directories such as `packages/test` the script specs were using.
